# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'ShoppingApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShoppingApp


   pod 'AFNetworking', '~> 3.0'
   pod 'SDWebImage', '~>3.8'
   
  target 'ShoppingAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMockito', '~> 4.0'
  end

  target 'ShoppingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
